### ISSUE TITLE
PairT monad transformer?

### ISSUE THREAD

**Issue by adelbertc** [conal/uniform-pair#6]
Unsure if I need this but found myself implementing it if only for fun. Seems you can define a couple instances for it, including `Monad` though that one is a bit weird.. needs a way to compose `f (Pair a)`'s.. perhaps a `Semigroup` constraint?

Here's some code I have:

```haskell
pureG :: Monad f => a -> f (Pair a)
pureG a = pure $ a :# a

bindG :: (Monad f, Semigroup b) => f (Pair a) -> (a -> f (Pair b)) -> f (Pair b)
bindG fpa f = fpa >>= f'
  where f' (x :# y)     = combine (f x) (f y)
        -- combine :: f (Pair b) -> f (Pair b) -> f (Pair b)
        combine = liftA2 (<>)

data PairT f a = PairT (f (Pair a))

instance Functor f => Functor (PairT f) where
  fmap f (PairT fpa) = PairT $ fmap (fmap f) fpa
```

**EDIT** Oh wait wouldn't work since it wouldn't be forall b (Semigroup constraint). Boo.

**Comment by conal** [comment]
I don't know who'd want a monad transformer for `Pair`. If so, I think there's a single compelling instance defined via a type class morphism that applies uniformly to *all* representable functors (of which `Pair` is one).

**Comment by adelbertc** [comment]
I think I understand - the `PairT` monad transformer, if it exists, would just be the monad transformer-y thing for representable functors specialized to `Pair`.

If so, looks like there is such a thing through `Compose`, from https://hackage.haskell.org/package/representable-functors-3.2.0.2/docs/Data-Functor-Representable.html :

```haskell
(Representable f, Representable g) => Representable (Compose f g)

pureRep :: Representable f => a -> f a

bindRep :: Representable f => f a -> (a -> f b) -> f b
```

Unfortunately the particular stack I was thinking of when I filed this ticket was `Compose Maybe Pair` but `Maybe` isn't representable so boo. But very instructive exercise in denotational design! :-)

**Comment by conal** [comment]
If `Applicative` suffices, then `Compose Maybe Pair` would work, since `Applicative` is closed under composition. The representable nature of `Pair` determines the `Applicative` instance. If you wanted `Pair (Maybe t)` (equivalently `MaybeT Pair t`) instead of `Maybe (Pair t)`, then you'd also get a `Monad` instance via the representability isomorphism between `Pair` and `(->) Bool` (or `Reader Bool`).

**Comment by adelbertc** [comment]
Yep Applicative should be interesting enough. My main motivation for going down this route was primarily "does the denotation give a Monad instance and if so how does that translate to my data type?" Since it doesn't I'll just move on until I hit a snag needing Monad or something, as you suggested in your LambdaJam talk :-)
